### ISSUE TITLE
Some code actions don't work

### ISSUE THREAD

**Issue by sgwilym** [sgwilym/nova-deno#1]
It seems that most code actions don't work. Nova's `LanguageClient` probably isn't able to handle the result, and I've logged the issue [here](https://devforum.nova.app/t/code-actions-not-working-with-deno-lsp-how-can-i-diagnose/1058/2).

**Comment by jaydenseric** [comment]
Is this issue tracking this problem, where the cache code action does work and results in extension console errors?

<img width="1080" alt="Screen Shot 2021-08-03 at 12 02 02 pm" src="https://user-images.githubusercontent.com/1754873/127946030-a2c844db-3e8b-4e1a-985c-c9b849ece964.png">

**Comment by sgwilym** [comment]
Yup. Basically all code actions don't work right now. For now, you'll need to cache using 'Cache dependencies' command from the command palette.

**Comment by belcar-s** [comment]
Code actions still don't seem to work for me 🙁. I'm using Nova 9.3.

https://user-images.githubusercontent.com/73370025/163695356-18f73de0-6187-497b-a3a0-6cc0acdaf452.mov

**Comment by sgwilym** [comment]
I've also noticed some weirdness around this, because some code actions work - like adding a missing import. I think I'll have to do some digging here, and I have a feeling this might need changes from Nova's side too, so bear with me.

**Comment by belcar-s** [comment]
Here are some messages I got after trying to cache a dependency:

<img width="333" alt="Screen Shot 2022-04-21 at 12 33 41 PM" src="https://user-images.githubusercontent.com/73370025/164518117-6f5ae5f5-19b7-4876-8352-fc0471967f1f.png">
<img width="665" alt="Screen Shot 2022-04-21 at 12 34 01 PM" src="https://user-images.githubusercontent.com/73370025/164518126-37fc75df-f3e4-498e-80fc-8bd07dc249f8.png">

**Comment by sgwilym** [comment]
Superseded by #31
