### ISSUE TITLE
Add support for accepting Deno more command-line arguments

### ISSUE THREAD

**Issue by atdrendel** [sgwilym/nova-deno#10]
In our main project, we make heavy use of [import maps](https://deno.land/manual@v1.12.2/linking_to_external_code/import_maps), which can be specified via the CLI argument `--import-map <FILE>`. [The extension already supports the `--unstable` flag](https://github.com/sgwilym/nova-deno/blob/2259b3070f5d5aadbc471d2672ec22da07f83ef9/src/nova_deno.ts#L33). Maybe add similar support for `--import-map <FILE>`, `--lock <FILE>`, `--lock-write`, and other common flags?

**Comment by sgwilym** [comment]
It'll be fairly easy to add support for per-project tsconfig.json and import maps. Should happen soon. 👍

I think args like `--lock` only work with `deno run` and `deno bundle`, but I just added Task templates for those which have preferences where you can pass these kinds of options!

**Comment by atdrendel** [comment]
Great to hear. Thanks for working so hard on this.

**Comment by sgwilym** [comment]
Added this in a quick v0.3 which should be available for download shortly. Let me know if this meets your needs!

**Comment by atdrendel** [comment]
I just installed the new version of the extension, and the new preferences for the import map and tsconfig work well. Thanks, again, for taking care of this issue.
