### ISSUE TITLE
No Intellisense when typing

### ISSUE THREAD

**Issue by kresdjan** [sgwilym/nova-deno#15]
I am sure the problem is with me and not the extension. I cannot the "Intellisense" working. I have disabled the [TypeScript extension]( https://github.com/apexskier/nova-typescript). Code formatting and listing works, but I get no Intellisense when typing. 

Do I need to install a module?  

Version: 0.3.4

**Comment by sgwilym** [comment]
You’re not doing anything wrong, currently there’s only autocomplete on certain characters like `.`. There a mismatch between what Nova requests from the language server and what the LSP expects, which @robb-j investigated in [this issue](https://github.com/denoland/deno/issues/10966). 

Really what we’re hoping for is a fix from Nova. There is a thread in the dev forums [here](https://devforum.nova.app/t/bug-with-textdocument-completion/969).

I share your frustration!

**Comment by kresdjan** [comment]
@sgwilym Thanks for clarifying. Lets hope that Nova gets around to fixing this.

**Comment by sgwilym** [comment]
Going to reopen this as it’s good to track..

**Comment by sgwilym** [comment]
Fixed by the release of Nova 9.
