### ISSUE TITLE
Expects a workspace path

### ISSUE THREAD

**Issue by belcar-s** [sgwilym/nova-deno#20]
<img width="715" alt="Screen Shot 2022-04-21 at 12 07 54 AM" src="https://user-images.githubusercontent.com/73370025/164376276-9d3950b9-2820-4a95-bee0-1225e39bbc02.png">

Pressing ⇧⌘N opens windows that aren't associated to any folder, and opening a JavaScript file in one of those windows prompts the extension to crash.

The little arrow shown in the screenshot leads you to the following lines of code. I think `join` is throwing when `workspacePath` is nullish.

```JS
const workspacePath = nova.workspace.path;
const denoConfigPath = nova.path.join(workspacePath, "deno.json");
const configWatcher = nova.fs.watch(denoConfigPath, () => {
  taskDisposable.dispose();
  taskDisposable.add(registerDenoTasks());
  nova.commands.invoke("co.gwil.deno.commands.restartServer");
});
```

The solution might simply be to skip those lines if there's no `workspace.path` :).  Unfortunately, there seems to be similar code elsewhere; solving this issue could be a little harder.

**Comment by sgwilym** [comment]
Oh that's interesting, I'd never considered this case with the new window.

Yeah I'll just skip watching if there's no path. I think once a workspace would become defined the extension would reactivate, so no need to do anything else (?)

**Comment by belcar-s** [comment]
> I think once a workspace would become defined the extension would reactivate, so no need to do anything else (?)

Yup. I tested this with an extension whose `activate` function just prints the workspace path:

https://user-images.githubusercontent.com/73370025/164490871-42b32e16-2128-48e5-ba95-165fd65e5447.mov

I was worried it would be more complicated because I saw this code in `DenoTaskAssistant`. I missed the return statement :).

```TS
class DenoTaskAssistant implements TaskAssistant {
  provideTasks() {
    const workspacePath = nova.workspace.path;

    if (!workspacePath) {
      return [];
    }
```

I'm glad it's easy to fix, though I wonder why TypeScript didn't catch it.
