### ISSUE TITLE
Import module error

### ISSUE THREAD

**Issue by evamango** [sgwilym/nova-deno#29]
My project's structure is simple, and I receive an error after import a module.
![image](https://user-images.githubusercontent.com/3355751/169511109-5a35245c-b1ce-4c41-aa52-04ed13f6b8c9.png)

How to config the import service?

Also, How to config the formatter/linter, I don't like the semi at the end of line.
THX!!

**Comment by evamango** [comment]
Almost forgot, my Nova version is 9.3.
THX!

**Comment by jaydenseric** [comment]
Write the full path the module you are importing, i.e:

```js
import foo from "./foo.ts";
```

Regarding your formatting preferences, that sort of thing is managed in a [Deno config file](https://deno.land/manual/getting_started/configuration_file). I don't know if there is a preference regarding no semi, and I suggest you stick to the defaults as much as possible anyway.

**Comment by sgwilym** [comment]
Hello @evamango!

Deno's a bit different to Node. For example: you don't need a `package.json`, `tsconfig.json`, or even `node_modules`.

Deno also doesn't support what are called _bare specifiers_, e.g. `import { something } from "something"`. You always need a file extension. Even third party modules are imported this way: `import { something } from "https://deno.land/x/something/mod.ts"`.

[You can find out more in the Deno manual](https://deno.land/manual).

+1 to wot @jaydenseric says. Also there's no way to configure `deno fmt` to not use semicolons, though [of course there's an open issue](https://github.com/denoland/deno/issues/13616).

**Comment by evamango** [comment]
Thank a lot!
