### ISSUE TITLE
deno.cache command results in 'method not found' alert 

### ISSUE THREAD

**Issue by sgwilym** [sgwilym/nova-deno#31]
Not sure if this is an issue with Nova or the Deno LSP honestly.

![790bc4920a038072c5e70f0dbad1a50ff80952dc](https://user-images.githubusercontent.com/579491/169839282-fb85670d-b4b4-4107-962a-8006289df8c3.gif)

```
Deno Language Server[15:32:40.040000] Sending JSON-RPC request: 82 workspace/executeCommand
{
  "jsonrpc" : "2.0",
  "id" : 82,
  "method" : "workspace\/executeCommand",
  "params" : {
    "command" : "deno.cache",
    "arguments" : [
      [
        "https:\/\/deno.land\/std\/bytes\/bytes_list.ts"
      ]
    ]
  }
}

Deno Language Server[15:32:40.040000] Got a workspace/executeCommand request, but it is not implemented

Deno Language Server[15:32:40.087000] Received JSON-RPC response: 82 workspace/executeCommand
{
  "error" : {
    "message" : "Method not found",
    "code" : -32601
  },
  "id" : 82,
  "jsonrpc" : "2.0"
}

Deno Language Server[15:32:40.087000] -32601 Method not found```

**Comment by belcar-s** [comment]
I don't know if this information is novel, but I think I've confirmed that the Visual Studio Code extension registers a `deno.cache` command, which is somehow invoked when the code action is selected.

![extension console showing a message indicating the execution of the `deno.cache` command registered by the Deno Visual Studio Code extension](https://user-images.githubusercontent.com/73370025/171296456-8a079cf8-5222-4627-aa02-e802d98d9f65.png)

Registering a `deno.cache` command ourselves doesn't work, as described here: https://devforum.nova.app/t/lsp-executecommand-and-method-not-found-alert-whos-requesting-who/1650/4

Maybe this requires Nova to imitate VS Code's behavior, which is supposedly to execute extension-registered commands in response to certain LSP requests (?).

**Comment by sgwilym** [comment]
As of Nova 11.7 and Deno 1.38.5, this seems to have been fixed!!!
