### ISSUE TITLE
Hit the shortcut of "show complete content" does not trigger the import suggestion.

### ISSUE THREAD

**Issue by evamango** [sgwilym/nova-deno#37]
I have a simple module named "foo".
![image](https://user-images.githubusercontent.com/3355751/170176495-e17215a6-663a-476c-bb2f-33fd659263dd.png)

And wanna import to use it in another file. I type "foo" and hit the shortcut, nothing happened finally.
![image](https://user-images.githubusercontent.com/3355751/170176750-28c43cea-8800-4c6c-b157-8927f207fcd1.png)

I Expect to show an import suggestions list to let me select which module to be imported, then add the import code automatically. Like:
![image](https://user-images.githubusercontent.com/3355751/170177200-c6571d57-5e98-4e87-8af4-00d2669e35bb.png)

THX!

os: macos 12.3.1
nova: 9.3

**Comment by belcar-s** [comment]
Hmm. Is this what you're referring to?

https://user-images.githubusercontent.com/73370025/170585163-041bae65-647f-4a1a-8c98-632fc0bbbe09.mov

You can make that list of options appear by pressing ⌃⌘A (control-command-A). You can also click the light bulb.

**Comment by evamango** [comment]
> Hmm. Is this what you're referring to?
> 
>  Screen.Recording.2022-05-26.at.16.44.06.mov 
> You can make that list of options appear by pressing ⌃⌘A (control-command-A) or by clicking on the light bulb.

Sooooooga. The action is "Show code action".
Em...Haven't I tried this before?

Many Thanks!
