### ISSUE TITLE
Strangely, Deno config files are parsed a million times

### ISSUE THREAD

**Issue by belcar-s** [sgwilym/nova-deno#40]
Every time a Deno configuration file is saved, the code that adds tasks to the tasks menu is run an amazing number of times 🙂.

<img width="1552" alt="screen shot that shows the same parse error, repeated in the console" src="https://user-images.githubusercontent.com/73370025/173988645-c5028347-6287-4997-be33-d997383db58d.png">

**Comment by sgwilym** [comment]
Fixed this!
