### ISSUE TITLE
The plugin doesn't seem to be loading my deno.json file

### ISSUE THREAD

**Issue by davidbdyer** [sgwilym/nova-deno#43]
The plugin doesn't seem to be loading my deno.json file from the root of my project directory. I really don't like using double qoutes in my JS files. 
```json
{
  "options": {
     "singleQuote": true,
  }
}
```

**Comment by sgwilym** [comment]
What you have is not quite a valid deno.json. Fortunately you can fix this yourself:

```json
{ 
  "fmt": {
    "options": {
       "singleQuote": true,
    }
  }
}
```
