### ISSUE TITLE
Error converting specifier settings: invalid type: null, expected struct SpecifierSettings

### ISSUE THREAD

**Issue by JDENredden** [sgwilym/nova-deno#47]
When I start the extension my logs fill up with the following error

`Error converting specifier settings: invalid type: null, expected struct SpecifierSettings`

I installed Deno fresh for this extension, never used it before, using `brew install deno`.

I think I am missing a middle step, but I'm not sure what it is. Any advice on setting up for the first time?

![CleanShot 2023-10-13 at 16 57 40](https://github.com/sgwilym/nova-deno/assets/672800/ff54b3ff-bd2f-4a64-a5ac-a67cb581c7d5)

**Comment by sgwilym** [comment]
Hi @JDENredden, thanks for the report. I don't think you're doing anything wrong, this is probably the extension not passing some options where it should. I will check this out!

**Comment by sgwilym** [comment]
I've just published v1.4.0 of the extension. Let me know if it solves the problem for you!

**Comment by JDENredden** [comment]
Just installed and the error in the logs has gone away. So far so good. Will report back after a day if I run into anything else.
