### ISSUE TITLE
Linting not working

### ISSUE THREAD

**Issue by jaydenseric** [sgwilym/nova-deno#8]
In a project with a mix of `.js` and `.jsx` files, no lint warnings or errors appear in the editor if you do mistakes, e.g. bad syntax.

In VS Code using the official Deno extension such lint errors are reported in the editor, so I don't think it's a problem with my Deno project.

I haven't tried `.ts` or `.tsx` files yet with Nova and this extension, so I don't know if they lint as expected.

**Comment by jaydenseric** [comment]
Ok, linting is not working for `.ts` files either:

<img width="446" alt="Screen Shot 2021-07-29 at 11 34 39 am" src="https://user-images.githubusercontent.com/1754873/127417930-85c9a071-e5fd-427e-9de2-98965f091df0.png">

Does it need to be enabled somehow?

I'm using the latest Deno, and the CLI is installed:

```
$ deno --version
deno 1.12.2 (release, x86_64-apple-darwin)
v8 9.2.230.14
typescript 4.3.5
```

**Comment by jaydenseric** [comment]
Possible clues...

When I open a Nova Deno project with an open `.js` file, here is what appears in the extension console:

<img width="766" alt="Screen Shot 2021-07-29 at 11 43 15 am" src="https://user-images.githubusercontent.com/1754873/127418625-e75450c3-da34-4ecd-85c1-8c537f451887.png">

With a `.jsx` file:

<img width="763" alt="Screen Shot 2021-07-29 at 11 44 26 am" src="https://user-images.githubusercontent.com/1754873/127418651-ac42aed2-b07b-49aa-9b58-73e44646b7d7.png">

**Comment by jaydenseric** [comment]
Issue persists after downgrading Deno to the version mentioned in the extension readme:

```
deno upgrade --version 1.10.3
```

**Comment by sgwilym** [comment]
I think I've fixed this in v0.2 when I refactored user configurations. It should be up in the extension library soon, so let me know if it fixes the issue for you.

**Comment by sgwilym** [comment]
@jaydenseric Are you still having this problem?

**Comment by jaydenseric** [comment]
I think this is working now, thanks for your work :)

I've been on Node.js projects the past few days, but am back on Deno work again now so I'll be able to try out the fix more thoroughly. I did notice the other day the linting wasn't working for a bit, but I managed to coax it into working again by restarting the editor or something, I can't remember. If it happens again I'll report back.
